name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Change current directory
      run: cd ${{ github.workspace }}/src
    - name: Restore dependencies
      run: |
        cd ${{ github.workspace }}/src
        dotnet restore
    - name: Build
      run: |
        cd ${{ github.workspace }}/src
        dotnet build --no-restore
    - name: Test
      run: |
        cd ${{ github.workspace }}/src
        dotnet test --no-build --verbosity normal
